import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "../globals.css";
import Header from "@/components/global/header";
import Footer from "@/components/global/footer";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snappers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="relative">
          <Header />
          <div className="bg-snappers-bg bg-cover h-full md:h-screen">
            {children}
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
