import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "../globals.css";
import Header from "@/components/global/header";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/global/footer";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snappers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative">
            <Header />
            <div className="container  py-10">{children}</div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
